if message.content.startswith("ik ben een vreselijk idioot persoon"):
    await pre_game(msg_placeholder)

async def pre_game(x):
    await x.channel.send("Het is nacht in Wakkerdam")
    await x.channel.send("Iedereen gaat slapen")
    await x.channel.send("Cupido wordt wakker en wijst twee liefjes aan")
    await x.channel.send("Nadat Cupido zijn pijl in 2 personen hun anussen heeft gestoken gaat hij blij slapen.")
    await x.channel.send(
        "De twee geliefden schrikken wakker van de pijlen in hun kontjes en kijken elkaarl iefdevol aan")
    await x.channel.send("De geliefden kruipen bij elkaar in bed en gaan lekker slapen")
    await x.channel.send("De Ziener wordt wakker na een slecht voorgevoel in de buik")
    await x.channel.send("Zo paranoïa dat ie is, loopt hij naar zijn glazen bol en ziet hij 1 iemands ware zelf")
    await x.channel.send("Na zoiets schokkends te zien valt de ziener flauw en is hij buitenbewustzijn")
    await x.channel.send("De Weerwolven worden honerig en besloten op jacht te gaan")
    await x.channel.send("Wiens kontje zullen ze opeten?")
    await x.channel.send("Na heerlijk gesmikkeld te hebben vallen ze in slaap")
    await x.channel.send("De heks wordt wakker door de stank van een aangebrand soepje.")
    await x.channel.send("Ze ziet haar levensdrankje en vergif staan.")
    await x.channel.send("Wil ze misschien 1 van die 2 gebruiken?")
    await x.channel.send("Na deze uitbundige keuze valt ze in slaap")
    await x.channel.send("Het is dag in Wakkerdam")
    await x.channel.send("Iedereen wordt wakker behalve ...")
    await x.channel.send("Na te leren dat er weerwolven zijn in de stad hebben de burgers een burgermeester nodig.")
    await x.channel.send("Wie wilt burgermeester worden?")
    await x.channel.send("Maak je speech ...")
    await x.channel.send("Stem op wie jij de burgermeester wilt hebben")
    await x.channel.send("... is de burgermeester geworden. Gefeliciteerd")
    await x.channel.send("Iemand iets sus gezien?")
    await x.channel.send("Stem iemand eruit")
    await x.channel.send("... is opgehangen en was een ...")